docs: specify remote bookmark in bookmark@remote form
So that the `jj bookmark track` command does not error in the tutorial
"Using Jujutsu with GitHub and GitLab Projects".

Before this change the command is:

  jj bookmark track bar

Output:

  error: invalid value 'bar' for '<BOOKMARK@REMOTE>...': remote bookmark must be specified in bookmark@remote form

  For more information, try '--help'.

After this change the command is:

  jj bookmark track bar@origin

Output:

  Started tracking 1 remote bookmarks.