config schema: Fix "valid under more than one of the schemas" error
Since `aliases.<name>.enabled` is a boolean that can be `true` or
`false`, this meant that sometimes certain aliases could apply to both
of the later `oneOf` conditions. To address this, the condition with
`definition` was made to be a const `true`, making it always
incompatible with the condition of `enabled` as const `false`. By
default JSON schemas allow additional fields, so changing an existing
alias table to have `aliases.<name>.enabled = false` works, as well as
an entirely new `aliases.no-op-alias.enabled = false`. Another option
would have been to use `"if"`/`"then"`, but the top of the file says
"`taplo` ... only support[s] version draft-04 of JSON Schema", and
if/then/else is a draft-07 feature.

Verified this change with:

```console
$ taplo lint ~/.config/jj/{,conf.d/,repos/*/,workspaces/*/}*.toml \
    --schema file://"$(realpath cli/src/config-schema.json)"
$ echo $?
0
```

Example config that fails with the latest (0.46.0) schema:

```toml
[aliases]
test1.definition = ["version"]

test2.doc = "my alias"
test2.definition = ["version"]
```

```console
$ taplo lint test.toml --schema https://docs.jj-vcs.dev/0.46.0/config-schema.json
 INFO taplo:lint_files:collect_files: found files total=1 excluded=0 files=["/path/to/test.toml"] cwd="<redacted>"
error: {"definition":["version"]} is valid under more than one of the schemas listed in the 'oneOf' keyword
  ┌─ /path/to/test.toml:2:1
  │
2 │ test1.definition = ["version"]
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ {"definition":["version"]} is valid under more than one of the schemas listed in the 'oneOf' keyword
... and 9 more errors ...
```