gerrit upload: don't error when unrelated links are present
jj gerrit upload would error when any link is present, even if they are
not recognized as gerrit links: filter for '/id/I' as per the split_once
check that follows.

This fixes the following error when any Link trailer is present:
> Error: Multiple Change-Id footers in revision yvkyokmoywqk

Fixes: 38fed24fc236 ("gerrit upload: support the alternative `Link` change-id trailer")